name: ai
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  intl: ^0.19.0

  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2
  smooth_page_indicator: ^2.0.1
  dio: ^5.3.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Gemini_Generated_Image_hwhxvlhwhxvlhwhx.png
    - assets/images/7611770.png
    - assets/images/images.png
    - assets/images/Google__G__logo.svg.webp
    - assets/images/unnamed.jpg
    - assets/videos/jumping_jacks.gif
    - assets/videos/pull_ups.gif
    - assets/videos/push_up.gif
    - assets/videos/russian_twists.gif
    - assets/videos/squats.gif