// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx63Ks9H1J7s9ooq4wvplVyI6VOkNSt5c',
    appId: '1:752714412940:web:4179545eb2e3fb11c1dca9',
    messagingSenderId: '752714412940',
    projectId: 'fitnessapp-f336e',
    authDomain: 'fitnessapp-f336e.firebaseapp.com',
    storageBucket: 'fitnessapp-f336e.firebasestorage.app',
    measurementId: 'G-SKV2153B3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASdeWIBf4lPjOp-ugO_FJniw8Z8h0De5I',
    appId: '1:752714412940:android:0a3474ef32aa9979c1dca9',
    messagingSenderId: '752714412940',
    projectId: 'fitnessapp-f336e',
    storageBucket: 'fitnessapp-f336e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADU1STD85IB9fDQigw7I-PHLpOnLp__T8',
    appId: '1:752714412940:ios:a8dc08a4d64dfb68c1dca9',
    messagingSenderId: '752714412940',
    projectId: 'fitnessapp-f336e',
    storageBucket: 'fitnessapp-f336e.firebasestorage.app',
    iosBundleId: 'com.example.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADU1STD85IB9fDQigw7I-PHLpOnLp__T8',
    appId: '1:752714412940:ios:a8dc08a4d64dfb68c1dca9',
    messagingSenderId: '752714412940',
    projectId: 'fitnessapp-f336e',
    storageBucket: 'fitnessapp-f336e.firebasestorage.app',
    iosBundleId: 'com.example.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx63Ks9H1J7s9ooq4wvplVyI6VOkNSt5c',
    appId: '1:752714412940:web:6361ec2d36bf62acc1dca9',
    messagingSenderId: '752714412940',
    projectId: 'fitnessapp-f336e',
    authDomain: 'fitnessapp-f336e.firebaseapp.com',
    storageBucket: 'fitnessapp-f336e.firebasestorage.app',
    measurementId: 'G-P05EV7K2NM',
  );
}
